version: "3.9"

services:
  vm1:
    image: debian:11
    container_name: vm1
    hostname: vm1
    networks:
      my_network:
        ipv4_address: 192.168.1.10
    ports:
      - "2221:2222"
    volumes:
      - ./setup.sh:/setup.sh
    command: [ "/bin/bash", "-c", "chmod +x /setup.sh && bash /setup.sh" ]
    privileged: true

  vm2:
    image: debian:11
    container_name: vm2
    hostname: vm2
    networks:
      my_network:
        ipv4_address: 192.168.1.20
    ports:
      - "2222:2222"
    volumes:
      - ./setup.sh:/setup.sh
    command: [ "/bin/bash", "-c", "chmod +x /setup.sh && bash /setup.sh" ]
    privileged: true

  vm3:
    image: debian:11
    container_name: vm3
    hostname: vm3
    networks:
      my_network:
        ipv4_address: 192.168.1.30
    ports:
      - "2223:2222"
    volumes:
      - ./setup.sh:/setup.sh
    command: [ "/bin/bash", "-c", "chmod +x /setup.sh && bash /setup.sh" ]
    privileged: true

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
